### ISSUE TITLE
.github is a public organization repo

### ISSUE THREAD

**Issue by YigitDemirag** [EIS-Hub/.github#1]
Thanks @karthik-charan , this is a really nice initiative. Very-well written :)

But if we create a `.github` it will be the **public face** of EIS-Hub, which shouldn't include technical stuff but maybe explain what EIS-Hub is for with contact email address etc. And if we make this repo private, it won't act as an organisation README.md and will lose its purpose.

I think alternatively, we can create a separate `guidelines` repository, which includes multiple .md files e.g. `jax_install_snnmonster.md`, `hyper_parameter_tools.md` or so capturing some well-written technical notes. What do you think?

**Comment by karthik-charan** [comment]
@YigitDemirag 
Yes! I was a bit sceptical about this as well, but went ahead with it!
Your suggestion makes perfect sense!
I will do this right away! 😸

**Comment by YigitDemirag** [comment]
Great. Looks really nice, thanks 👍
